//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class BBSDescriptionData {
    
    private BBSDescriptionDataTacticalCallSign[] tacticalCallSignField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TacticalCallSign")]
    public BBSDescriptionDataTacticalCallSign[] TacticalCallSign {
        get {
            return this.tacticalCallSignField;
        }
        set {
            this.tacticalCallSignField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BBSDescriptionDataTacticalCallSign {
    
    private BBSDescriptionDataTacticalCallSignOriginalDescription originalDescriptionField;
    
    private BBSDescriptionDataTacticalCallSignNewDescription newDescriptionField;
    
    private string primaryField;
    
    private string secondaryField;
    
    private string frequenciesField;
    
    /// <remarks/>
    public BBSDescriptionDataTacticalCallSignOriginalDescription OriginalDescription {
        get {
            return this.originalDescriptionField;
        }
        set {
            this.originalDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public BBSDescriptionDataTacticalCallSignNewDescription NewDescription {
        get {
            return this.newDescriptionField;
        }
        set {
            this.newDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string primary {
        get {
            return this.primaryField;
        }
        set {
            this.primaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string secondary {
        get {
            return this.secondaryField;
        }
        set {
            this.secondaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string frequencies {
        get {
            return this.frequenciesField;
        }
        set {
            this.frequenciesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BBSDescriptionDataTacticalCallSignOriginalDescription {
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BBSDescriptionDataTacticalCallSignNewDescription {
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}
